;PSPad user HighLighter definition file
[Settings]
Name=HTAccess
HTMLGroup=0
Vectors=0
Label=0
PHPVariable=0
RubySymbols=0
FileType=.htaccess
CommentString=#
SharpComment=1
IndentChar=
UnIndentChar=
TabWidth=0
SingleQuote=1
DoubleQuote=0
ApostropheQuote=0
KW1StartWith=0
KW2StartWith=0
KW3StartWith=0
KW4StartWith=0
EscString=0
EscChar=\
KeyWordChars=_/:
CodeExplorer=ftUnknown
CodeFolding=ftNone
DocComment=
[KeyWords]
AcceptFilter=
AcceptPathInfo=
AccessFileName=
Action=
AddAlt=
AddAltByEncoding=
AddAltByType=
AddCharset=
AddDefaultCharset=
AddDescription=
AddEncoding=
AddHandler=
AddIcon=
AddIconByEncoding=
AddIconByType=
AddInputFilter=
AddLanguage=
AddType=
Alias=
AliasMatch=
Allow=
AllowOverride=
AuthBasicProvider=
AuthDBMUserFile=
AuthDigestProvider=
AuthFormAuthoritative=
AuthFormProvider=
AuthFormSize=
AuthFormUsername=
AuthGroupFile=
AuthMerging=
AuthName=
AuthnProviderAlias=
AuthType=
AuthUserFile=
AuthzProviderAlias=
AuthzSendForbiddenOnFailure=
DefaultLanguage=
Deny=
Directory=
ErrorDocument=
ExpiresActive=
ExpiresByType=
ExpiresDefault=
Files=
FilesMatch=
ForceType=
Header=
IfModule=
Location=
MimeMagicFile=
ModMimeUsePathInfo=
MultiviewsMatch=
Options=
Order=
Redirect=
RedirectMatch=
RedirectPermanent=
RedirectRelative=
RedirectTemp=
RequestHeader=
Require=
RequireAll=
RequireAny=
RequireNone=
RewriteBase=
RewriteCond=
RewriteEngine=
RewriteMap=
RewriteOptions=
RewriteRule=
Satisfy=
ScriptAlias=
ScriptAliasMatch=
SetHandler=
TypesConfig=
[ReservedWords]
API_VERSION=
CONN_REMOTE_ADDR=
CONTEXT_DOCUMENT_ROOT=
CONTEXT_PREFIX=
ENV=
HTTPS=
HTTP_ACCEPT=
HTTP_COOKIE=
HTTP_FORWARDED=
HTTP_HOST=
HTTP_PROXY_CONNECTION=
HTTP_REFERER=
HTTP_USER_AGENT=
IS_SUBREQ=
LA-F=
LA-U=
PATH_INFO=
QUERY_STRING=
REMOTE_ADDR=
REMOTE_HOST=
REMOTE_IDENT=
REMOTE_PORT=
REMOTE_USER=
REQUEST_FILENAME=
REQUEST_METHOD=
REQUEST_SCHEME=
REQUEST_URI=
SCRIPT_FILENAME=
SCRIPT_GROUP=
SCRIPT_USER=
SERVER_ADDR=
SERVER_ADMIN=
SERVER_NAME=
SERVER_PORT=
SERVER_PROTOCOL=
SERVER_SOFTWARE=
THE_REQUEST=
TIME=
TIME_DAY=
TIME_HOUR=
TIME_MIN=
TIME_MON=
TIME_SEC=
TIME_WDAY=
TIME_YEAR=
[KeyWords2]
A=
access=
add=
All=
always=
And=
append=
Basic=
days=
Default=
denied=
Digest=
echo=
edit=
env=
ExecCGI=
expr=
FollowSymLinks=
Form=
gone=
granted=
group=
host=
hours=
Includes=
IncludesNOEXEC=
Indexes=
ip=
local=
M=
merge=
method=
minutes=
modification=
months=
MultiViews=
None=
note=
now=
Off=
On=
Or=
permanent=
plus=
seconds=
seeother=
set=
setifempty=
SymLinksIfOwnerMatch=
temp=
unset=
user=
valid-user=
weeks=
years=
[KeyWords3]
