;PSPad user HighLighter definition file
[Settings]
Name=MADS
HTMLGroup=0
Vectors=0
Label=1
PHPVariable=0
RubySymbols=0
FileType=*.asm
CommentString=
BasComment=1
IndentChar=
UnIndentChar=
TabWidth=0
SingleQuote=1
DoubleQuote=1
ApostropheQuote=0
KW1StartWith=0
KW2StartWith=0
KW3StartWith=0
KW4StartWith=0
EscString=1
EscChar=\
KeyWordChars=_
CodeExplorer=ftMADS
CodeFolding=ftNone
DocComment=
[KeyWords]
ADB=
ADC=
ADD=
ADR=
ADW=
ALIGN=
AND=
ARRAY=
ASL=
BCC=
BCS=
BEQ=
BIT=
BMI=
BNE=
BPL=
BRA=
BRK=
BRL=
BVC=
BVS=
BY=
BYTE=
CLC=
CLD=
CLI=
CLV=
CMP=
COP=
CPX=
CPY=
DBYTE=
DEA=
DEC=
DEF=
DEFINE=
DEW=
DEX=
DEY=
DS=
DWORD=
ECHO=
EEND=
ELIF=
ELSE=
ELSEIF=
EN=
ENDA=
ENDE=
ENDIF=
ENDL=
ENDM=
ENDP=
ENDPG=
ENDR=
ENDS=
ENDW=
ENUM=
EOR=
ERROR=
EXIT=
EXTRN=
FL=
GET=
GLOBAL=
GLOBL=
HE=
HI=
IF=
INA=
INC=
INW=
INX=
INY=
JCC=
JCS=
JEQ=
JMI=
JML=
JMP=
JNE=
JPL=
JSL=
JSR=
JVC=
JVS=
LDA=
LDX=
LDY=
LEN=
LINK=
LO=
LOCAL=
LONG=
LSR=
MACRO=
MEND=
MVA=
MVN=
MVP=
MVX=
MVY=
MWA=
MWX=
MWY=
NOP=
NOT=
OR=
ORA=
PAGES=
PEA=
PEI=
PER=
PGEND=
PHA=
PHB=
PHD=
PHK=
PHP=
PHR=
PHX=
PHY=
PLA=
PLB=
PLD=
PLP=
PLR=
PLX=
PLY=
PRINT=
PROC=
PUBLIC=
PUT=
RCC=
RCS=
REG=
RELOC=
REND=
REP=
REPT=
REQ=
RMI=
RNE=
ROL=
ROR=
RPL=
RTI=
RTL=
RTS=
RVC=
RVS=
SAV=
SB=
SBB=
SBC=
SBW=
SCC=
SCS=
SEC=
SED=
SEI=
SEP=
SEQ=
SMI=
SNE=
SPL=
STA=
STP=
STRUCT=
STX=
STY=
STZ=
SUB=
SVC=
SVS=
SYMBOL=
TAX=
TAY=
TCD=
TCS=
TDC=
TRB=
TSB=
TSC=
TSX=
TXA=
TXS=
TXY=
TYA=
TYX=
UNDEF=
USE=
USING=
VAR=
WAI=
WDM=
WEND=
WHILE=
WO=
WORD=
XBA=
XCE=
XOR=
ZPVAR=
[ReservedWords]
DTA=
EIF=
ELI=
ELS=
END=
EQU=
ERT=
ICL=
IFT=
INI=
INS=
OPT=
ORG=
RUN=
SET=
[KeyWords2]
[KeyWords3]
